
"""Initial schema

Revision ID: 7b32e6fbe24e
Revises: 
Create Date: 2025-12-11 18:35:23.787375
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '7b32e6fbe24e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
